title: <p align="center"> Liana Al Bahri </p>

logo: "images/a2.jpg?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/liana-a-%F0%9F%93%8A-844389ba/">LinkedIn</a> |
  <a href="mailto:lianabhr1@gmail.com">Email</a> |

  </p>
  
  <p align="justify">My name is Liana and I am passionate about building data science and analytics solutions.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
