title: <p align="center"> Liana Al Bahri </p>

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/liana-a-%F0%9F%93%8A-844389ba/">LinkedIn</a> |
  <a href="mailto:lianabhr1@gmail.com">Email</a> |
  <a href="https://github.com/lianabhr">Github</a> |

  </p>
  
  <p align="justify">
  I'm a passionate data scientist. I am good at machine learning, statistic, and data visualization. I love solving tough problems and finding insights in data.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
